version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  backend:
    build: ./server
    restart: always
    ports:
      - 5000:5000
    environment:
      - MONGO_URI=mongodb://mongo:27017/clinic
    depends_on:
      - mongo
volumes:
  mongo-data: 